function [outray_ind,inray_ind] = get_ray_ind(angles,options)
	outray_ind = [find(angles>=options.angle_threshold&angles<=pi- options.angle_threshold);...
				  find(angles>=options.angle_threshold-pi&angles<=-options.angle_threshold)];
	inray_ind = [find(angles>=-options.angle_threshold&angles<=options.angle_threshold);...
				 find(angles>=pi-options.angle_threshold);...
				 find(angles<=-pi+options.angle_threshold)];
end